api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    eager_loading:
        enabled: true
    collection:
        pagination:
            page_parameter_name: _page
            items_per_page: 10
            client_items_per_page: true #disabled by default
            items_per_page_parameter_name: itemsPerPage
            #partial: true
            #client_partial: true
            #partial_parameter_name: 'partial'
    #     order_parameter_name: '_order' //zmiana nazyw parametru
